name: "Incremental Build"
on:
  push:
    branches: [ master ]

jobs:
  inc-build:
    name: "Build and Publish"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: "Cache Go modules"
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Build linux-amd64"
        run: |
          go build
          mv dockerhub_ratelimit_exporter ./container

      - name: "Build Image"
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository_owner }}/dockerhub_ratelimit_exporter
          tags: unstable ${{ github.sha }}
          context: ./container
          dockerfiles: |
            ./container/Containerfile

      - name: "Publish Image"
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}
