name: "Incremental Build"
on:
  push:
    branches: [ master ]

jobs:
  inc-build:
    name: "Build and Publish"
    runs-on: ubuntu-20.04
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: "Cache Go modules"
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Build linux-amd64"
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
          GO111MODULE: on
        run: go build -o container/dockerhub_ratelimit_exporter

      - name: "Get Git short Hash"
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: "Temp Buildah 1.20.0 fix"
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\"" > ~/.config/containers/storage.conf

      - name: "Build Image"
        id: build-image
        uses: redhat-actions/buildah-build@v2.5
        with:
          image: dockerhub_ratelimit_exporter
          tags: unstable ${{ env.SHORT_SHA }}
          oci: true
          context: ./container
          dockerfiles: |
            ./container/Containerfile

      - name: "Publish Image to ghcr.io"
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}

      - name: "Publish Image to quay.io"
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/k3rnel-pan1c
          username: k3rnel-pan1c+github_test
          password: ${{ secrets.RH_TOKEN }}
